# Generated by Django 5.1 on 2024-08-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=25, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("label", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, unique=True)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Niveau 1"),
                            (2, "Niveau 2"),
                            (3, "Niveau 3"),
                            (4, "Niveau 4"),
                            (5, "Niveau 5"),
                            (6, "Niveau 6"),
                            (7, "Niveau 7"),
                        ]
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialities",
                        to="base.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("register_number", models.CharField(max_length=25, unique=True)),
                ("birth_place", models.CharField(max_length=25)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                ("birth_at", models.DateTimeField()),
                (
                    "current_level",
                    models.IntegerField(
                        choices=[
                            (1, "Niveau 1"),
                            (2, "Niveau 2"),
                            (3, "Niveau 3"),
                            (4, "Niveau 4"),
                            (5, "Niveau 5"),
                            (6, "Niveau 6"),
                            (7, "Niveau 7"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="base.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(default=0)),
                ("is_normal", models.BooleanField(default=True)),
                ("inserted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notesEC",
                        to="base.schoolyear",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notesYear",
                        to="base.schoolyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="base.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=6, unique=True)),
                ("label", models.CharField(max_length=50)),
                ("credit", models.IntegerField(default=1)),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecs",
                        to="base.ue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UEProgramming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        choices=[(1, "Semestre 1"), (2, "Semestre 2")], default=1
                    ),
                ),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uesProgramedSpeciality",
                        to="base.speciality",
                    ),
                ),
                (
                    "ue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uesProgramed",
                        to="base.ue",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uesProgramedYear",
                        to="base.schoolyear",
                    ),
                ),
            ],
        ),
    ]
