# Generated by Django 5.1 on 2024-08-20 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_value_note_cc_note_ef_alter_note_ec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 20, 13, 28, 10, 266053)
            ),
        ),
    ]
