# Generated by Django 5.1 on 2024-08-23 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_note_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="year",
        ),
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
