# Generated by Django 5.1 on 2024-09-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_ec_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_at',
            field=models.DateField(),
        ),
    ]
